# .readthedocs.yml

# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required

version: 2

# Ensure the documentation is built using an appropriate version of Python
# and the right requirements (prairie requires Py3.9 at minimum because
# of the use of TypedDict among other things)

python:
  version: 3.11
  install:
    - requirements: requirements-dev.txt
