on: ["push", "pull_request"]

# Running tests with pytest in Python 3.8
name: pytest
jobs:
  pytest:
    name: pytest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]
        poetry-version: ["1.1.15"]
        os: ["ubuntu-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checking out latest version of master branch
        uses: actions/checkout@master

      - name: Install Python environment
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - name: Installing jpeg-dev and other Pillow dependencies with apt-get
        shell: bash
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y python3-dev python3-setuptools
          sudo apt-get install -y libtiff5-dev libjpeg8-dev libopenjp2-7-dev zlib1g-dev \
            libfreetype6-dev liblcms2-dev libwebp-dev tcl8.6-dev tk8.6-dev python3-tk \
            libharfbuzz-dev libfribidi-dev libxcb1-dev
          sudo apt-get install -y build-essential libsqlite3-dev \
            libpng-dev libjpeg-dev

      - name: Setup Python & Poetry and install project
        run: poetry install

      - name: Run pytest
        run: poetry run python -m pytest --cov=slacktivate --cov-branch tests/

      - name: Run codecov to upload report to site
        run: poetry run codecov -t ${{ secrets.CODECOV_TOKEN }}
