on: ["push", "pull_request"]

# Running tests with pytest in Python 3.8
name: pytest
jobs:
  pytest:
    name: pytest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Installing jpeg-dev and other Pillow dependencies with apt-get
        shell: bash
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y python3-dev python3-setuptools
          sudo apt-get install -y libtiff5-dev libjpeg8-dev libopenjp2-7-dev zlib1g-dev \
            libfreetype6-dev liblcms2-dev libwebp-dev tcl8.6-dev tk8.6-dev python3-tk \
            libharfbuzz-dev libfribidi-dev libxcb1-dev
          sudo apt-get install -y build-essential libsqlite3-dev \
            libpng-dev libjpeg-dev

      - name: Setup Python & Poetry and install project
        uses: abatilo/actions-poetry@v1.5.0
        with:
          python_version: 3.8.0
          poetry_version: 1.0
          working_directory: "." # optional, defaults to ".'
          args: install

      - name: Run pytest
        uses: abatilo/actions-poetry@v1.5.0
        with:
          python_version: 3.8.0
          poetry_version: 1.0
          working_directory: "."
          args: run python -m pytest --cov=slacktivate --cov-branch tests/

      - name: Run codecov to upload report to site
        uses: abatilo/actions-poetry@v1.5.0
        with:
          python_version: 3.8.0
          poetry_version: 1.0
          working_directory: "."
          args: run codecov -t ${{ secrets.CODECOV_TOKEN }}
